from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    HTTP_ERROR = "HTTP_ERROR"
    NOT_FOUND = "NOT_FOUND"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    BOOTSTRAP_FAILED = "BOOTSTRAP_FAILED"
    PROFILE_LIST_FAILED = "PROFILE_LIST_FAILED"
    PROFILE_LIMIT_EXCEEDED = "PROFILE_LIMIT_EXCEEDED"
    INVALID_DISPLAY_NAME = "INVALID_DISPLAY_NAME"
    INVALID_AGENT_PERSONALITY = "INVALID_AGENT_PERSONALITY"
    INVALID_WARNING_SENSITIVITY = "INVALID_WARNING_SENSITIVITY"
    INVALID_TTS_SPEED = "INVALID_TTS_SPEED"
    INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT"
    INVALID_PROFILE_SETTING = "INVALID_PROFILE_SETTING"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    INVALID_PROFILE_ID = "INVALID_PROFILE_ID"
    EMPTY_UPDATE_REQUEST = "EMPTY_UPDATE_REQUEST"
    ACTIVE_SESSION_EXISTS = "ACTIVE_SESSION_EXISTS"
    PROFILE_FILE_DELETE_FAILED = "PROFILE_FILE_DELETE_FAILED"
